import java.util.Scanner;
import java.text.DecimalFormat;

/**Program that calculates the value of inputted
value for x generated by an expression and displays
the number of digits to the left and right of the
decimal point.

Progect 3
@author Michael Duvall Comp 1210
@version 9/11/18
*/


public class FormulaEval {

/**Program that calulates value of x for a given expression
and prints number of digits to the left and right of the decimal
point.

@param args - standard command line
*/

   public static void main(String [] args) {
    
      double x;
      double resultNumerator, resultDenominator;
      Scanner input = new Scanner(System.in);
      int digitsLeft = 0;
      int digitsRight = 0;
      int resultLength = 0;
      DecimalFormat formatResult = new DecimalFormat("#,##0.0####");
   
   //Prompt user for x value
      System.out.print("Enter a value for x: ");
      x = input.nextDouble();
   
   //Evaluate the expression using imputed x.
      System.out.print("Result: ");
      resultNumerator = (1000 * x + Math.sqrt(Math.abs(3.9 * Math.pow(x, 5) 
         - Math.pow(x, 3) + 1)));
      
      resultDenominator = (1.6 * Math.pow(x, 2) + 2.7 * x + 3.8);
      
      double result = resultNumerator / resultDenominator;
      
      System.out.println(result);
      
      //Find # of characters to the left and right.
               
      String resultString = Double.toString(result);
      System.out.print("# of characters to left of decimal point: ");
      digitsLeft = resultString.indexOf(".");
      resultLength = resultString.length();
      System.out.println(digitsLeft);
      //Characters from right
      System.out.print("# of characters to right of decimal point: ");
      digitsRight = resultLength - digitsLeft - 1; 
      System.out.println(digitsRight);
      
      //Format the result "#,##0.0####"
      System.out.println("Formatted Result: " 
         + formatResult.format(result));
     
   }
}